services:
  - type: web
    name: quivr
    env: docker
    buildCommand: docker build -t quivr .
    startCommand: docker run -p 10000:10000 quivr
    envVars:
      - key: AWS_REGION
        value: eu-west-3
      - key: AWS_ACCESS_KEY_ID
        value: your_aws_access_key_id
        generateValue: false
      - key: AWS_SECRET_ACCESS_KEY
        value: your_aws_secret_access_key
        generateValue: false
    healthCheckPath: /
    numInstances: 1
    autoDeploy: true
    pullRequestPreviews: false
    branch: main
